### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mballaro** [ocean-data-challenges/2023a_SSH_mapping_OSE#1]
- [ ] Add comments/interpretations in notebooks
- [ ] Add more description on the various products
- [ ] Summarize key ocean variabilities solved in each product
- [x] Add data on MEOM server
- [ ] Provide lagrangian assessments DRIFTERS vs advected particle (see if it is doable with py-eddy-tracker package or test it with Parcels...)
- [ ] Qualitative assessment: comparison SSH/current maps vs observed CMEMS SST/chloro products (interactive maps hvplot,....)
